Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlePonto.Data;
using ControlePonto.Models;
using ControlePonto.Helpers;

namespace ControlePonto.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly Contexto _context;

        public FuncionarioController(Contexto context)
        {
            _context = context;
        }

        // GET: Funcionario
        public async Task<IActionResult> Index()
        {   
            
            return View(await _context.funcionario.ToListAsync());
        }


        public ActionResult BuscarCEP(string cep)
        {
           

            var result = new AjaxActionResult();

            try
            {

                var resultcep = Cep.BuscarCEP(cep);

                result.bag = resultcep;
                result.isOk = true;

            }
            catch (Exception ex)
            {
                result.isOk = false;
                result.message = ex.Message;
            }

            return Json(result);

        }

        // GET: Funcionario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.funcionario
                .FirstOrDefaultAsync(m => m.id == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // GET: Funcionario/Create
        public IActionResult Create()
        {
           

            return View();
        }

        // POST: Funcionario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Nome,CPF,Email,Telefone,Habilitacao,Categoria,LinguaEstrangeira,Estado,Cidade,CEP,Logradouro,Numero,Complemento,Cargo,SalarioProposto")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(funcionario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }

        // GET: Funcionario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.funcionario.FindAsync(id);
            if (funcionario == null)
            {
                return NotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("id,Nome,CPF,Email,Telefone,Habilitacao,Categoria,LinguaEstrangeira,Estado,Cidade,CEP,Logradouro,Numero,Complemento,Cargo,SalarioProposto")] Funcionario funcionario)
        {
            if (id != funcionario.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(funcionario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuncionarioExists(funcionario.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }

        // GET: Funcionario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.funcionario
                .FirstOrDefaultAsync(m => m.id == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // POST: Funcionario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var funcionario = await _context.funcionario.FindAsync(id);
            _context.funcionario.Remove(funcionario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FuncionarioExists(int? id)
        {
            return _context.funcionario.Any(e => e.id == id);
        }
    }
}

Controllers/HorarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlePonto.Data;
using ControlePonto.Models;

namespace ControlePonto.Controllers
{
    public class HorarioController : Controller
    {
        private readonly Contexto _context;

        public HorarioController(Contexto context)
        {
            _context = context;
        }

        // GET: Horario
        public async Task<IActionResult> Index()
        {
            var contexto = _context.HorarioModel.Include(h => h.Funcionario);
            return View(await contexto.ToListAsync());
        }

        // GET: Horario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horarioModel = await _context.HorarioModel
                .Include(h => h.Funcionario)
                .FirstOrDefaultAsync(m => m.HorarioID == id);
            if (horarioModel == null)
            {
                return NotFound();
            }

            return View(horarioModel);
        }

        // GET: Horario/Create
        public IActionResult Create()
        {
            ViewData["FuncionarioID"] = new SelectList(_context.funcionario, "id", "id");
            return View();
        }

        // POST: Horario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HorarioID,DiadaSemana,HoraInicio,HoraFim,TempodeDescanso,CargaHoraria,CargaHorariaSEmanal,FuncionarioID")] HorarioModel horarioModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(horarioModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FuncionarioID"] = new SelectList(_context.funcionario, "id", "id", horarioModel.FuncionarioID);
            return View(horarioModel);
        }

        // GET: Horario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horarioModel = await _context.HorarioModel.FindAsync(id);
            if (horarioModel == null)
            {
                return NotFound();
            }
            ViewData["FuncionarioID"] = new SelectList(_context.funcionario, "id", "id", horarioModel.FuncionarioID);
            return View(horarioModel);
        }

        // POST: Horario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HorarioID,DiadaSemana,HoraInicio,HoraFim,TempodeDescanso,CargaHoraria,CargaHorariaSEmanal,FuncionarioID")] HorarioModel horarioModel)
        {
            if (id != horarioModel.HorarioID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(horarioModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HorarioModelExists(horarioModel.HorarioID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FuncionarioID"] = new SelectList(_context.funcionario, "id", "id", horarioModel.FuncionarioID);
            return View(horarioModel);
        }

        // GET: Horario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horarioModel = await _context.HorarioModel
                .Include(h => h.Funcionario)
                .FirstOrDefaultAsync(m => m.HorarioID == id);
            if (horarioModel == null)
            {
                return NotFound();
            }

            return View(horarioModel);
        }

        // POST: Horario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var horarioModel = await _context.HorarioModel.FindAsync(id);
            _context.HorarioModel.Remove(horarioModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HorarioModelExists(int id)
        {
            return _context.HorarioModel.Any(e => e.HorarioID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControlePonto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ControlePonto</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Cadastro</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Horario" asp-action="Index">Horário</a>
                        </li>




                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ControlePonto - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)






    @*<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.js"></script>*@


    @*<script src="~/js/jquery.inputmask.js"></script>
        <script>

             $(document).ready(function () {
                $("#CPF").inputmask('999.999.999-99');
                $("#Telefone").inputmask('(99)99999-9999');
                 //$("#HoraInicio").inputmask('00:00:00');
                 //$("#HoraFim").inputmask('00: 00: 00');
            });

        </script>*@


    @*<script src="https://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script src="https://rawgit.com/RobinHerbots/Inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>*@





    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script src="https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js"></script>*@






    @*<script src="jquery.min.js" type="text/javascript"></script>
        <script src="jquery.maskMoney.js" type="text/javascript"></script>*@


    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script src="dist/jquery.maskMoney.min.js" type="text/javascript"></script>*@

    @*<script src="jquery.min.js" type="text/javascript"></script>
        <script src="jquery.maskMoney.js" type="text/javascript"></script>*@


    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script src="https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js"></script>*@


    @*<script>



            $(document).ready(function () {
                $('.date').mask('00/00/0000');
                $('.time').mask('00:00:00');
                $('.date_time').mask('00/00/0000 00:00:00');
                $('.cep').mask('00000-000');
                $('.Telefone').mask('(00)90000-0000');
                $('.phone_with_ddd').mask('(00) 0000-0000');
                $('.phone_us').mask('(000) 000-0000');
                $('.phone_br').focusout(function () {
                    var phone, element;
                    element = $(this);
                    element.unmask();
                    phone = element.val().replace(/\D/g, '');
                    if (phone.length > 10) {
                        element.mask("(99) 99999-9999");
                    } else {
                        element.mask("(99) 9999-99999");
                    }
                }).trigger('focusout');
                $('.mixed').mask('AAA 000-S0S');
                $('#CPF').mask('000.000.000-00', { reverse: true });
                $('.cnpj').mask('00.000.000/0000-00', { reverse: true });
                $('.money').mask('000.000.000.000.000,00', { reverse: true });
                $('.SalarioProposto').mask("#.##0,00", { reverse: true });
                $('.integer').mask("#.##0", { reverse: true });
                $('.ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
                    translation: {
                        'Z': {
                            pattern: /[0-9]/, optional: true
                        }
                    }
                });
                $('.ip_address').mask('099.099.099.099');
                $('.percent').mask('##0,00%', { reverse: true });
                $('.clear-if-not-match').mask("00/00/0000", { clearIfNotMatch: true });
                $('.placeholder').mask("00/00/0000", { placeholder: "<mark>/</mark>/<mark></mark>" });
                $('.fallback').mask("00r00r0000", {
                    translation: {
                        'r': {
                            pattern: /[\/]/,
                            fallback: '/'
                        },
                        placeholder: "<mark>/</mark>/<mark></mark>"
                    }
                });
                $('.selectonfocus').mask("00/00/0000", { selectOnFocus: true });
            });





        </script>*@














    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.js"></script>*@



    @*campo lingua estrangeira*@
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;display=swap">
    <link rel="stylesheet" href="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.20.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.20.0/css/mdb.min.css">
    <link rel="stylesheet" href="https://mdbootstrap.com/wp-content/themes/mdbootstrap4/docs-app/css/compiled-addons-4.20.0.min.css">
    <link rel="stylesheet" type="text/css" href="https://mdbootstrap.com/wp-content/themes/mdbootstrap4/css/mdb-plugins-gathered.min.css">
    <style></style>

    @*<div class="form-group">


            <ul id="select-options-8fd56ab7-fd42-40e4-982f-351a23bb110b" class="dropdown-content select-dropdown w-100 multiple-select-dropdown" style="display: none; max-height: 265.172px; width: 815px; position: absolute; top: 0px; left: 0px; opacity: 1;">
            </ul><select class="mdb-select colorful-select dropdown-primary md-form initialized" multiple="" searchable="Search here..">
                <option value="" disabled="" selected="">Choose your country2</option>
                <option value="1">USA</option>
                <option value="2">Germany</option>
                <option value="3">France</option>
                <option value="4">Poland</option>
                <option value="5">Japan</option>
            </select><label class="mdb-main-label active">Label example</label>
            <button class="btn-save btn btn-primary btn-sm waves-effect waves-light">Save</button>
        </div>*@


    <script type="text/javascript" src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.20.0/js/jquery.min.js"></script>
    <script type="text/javascript" src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.20.0/js/popper.min.js"></script>
    <script type="text/javascript" src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.20.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.20.0/js/mdb.min.js"></script>
    <script type="text/javascript" src="https://mdbootstrap.com/wp-content/themes/mdbootstrap4/docs-app/js/bundles/4.20.0/compiled-addons.min.js"></script>
    <script type="text/javascript" src="https://mdbootstrap.com/wp-content/themes/mdbootstrap4/js/plugins/mdb-plugins-gathered.min.js"></script>


    @*Mascara dos campos*@
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.js"></script>






    <script type="text/javascript">
        {// Material Select Initialization
            $(document).ready(function () {
                $('.mdb-select').materialSelect();
            });
        }</script>





    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.js"></script>*@











</body>
</html>